### PR TITLE
Added add-phone-number migration

### PR DESCRIPTION
**Pull request by beachsideproperty**
This pull request resolves steps 1 and 2 from issue #705.

### CODE REVIEW

**Comment by Alex-is-Gonzalez** [comment]
Great work the code looks great however it is in the wrong file!
We wanted to add the phone number to the existing Constituent table within: amplify/server/db/migrations/20220413154827_rename-volunteers-table-to-constituents.js

**Comment by Alex-is-Gonzalez** [comment]
# Database Migration

This migration file handles the changes related to renaming tables and adding a 'phone_number' column.

```javascript
const referencingTableName = 'sent_letters';
const oldTableName = 'volunteers';
const newTableName = 'constituents';

module.exports = {
  async up(knex) {
    // Step 1: Unbind the referencing table
    await knex.schema.alterTable(referencingTableName, (table) => {
      table.dropIndex(['volunteer_id']);
      table.dropForeign('volunteer_id');
    });

    // Step 2: Rename the primary table
    await knex.schema.renameTable(oldTableName, newTableName);

    // Step 3: Rebind the referencing table
    await knex.schema.alterTable(referencingTableName, (table) => {
      table.renameColumn('volunteer_id', 'constituent_id');
      table.foreign('constituent_id').references(`${newTableName}.id`);
      table.index(['constituent_id']);
    });

    // Step 4: Add the 'phone_number' column to the 'constituent' table
    await knex.schema.alterTable('constituent', (table) => {
      table.string('phone_number');
    });
  },

  async down(knex) {
    // Step 1: Unbind the referencing table
    await knex.schema.alterTable(referencingTableName, (table) => {
      table.dropIndex(['constituent_id']);
      table.dropForeign('constituent_id');
    });

    // Step 2: Rename the primary table
    await knex.schema.renameTable(newTableName, oldTableName);

    // Step 3: Rebind the referencing table
    await knex.schema.alterTable(referencingTableName, (table) => {
      table.renameColumn('constituent_id', 'volunteer_id');
      table.foreign('volunteer_id').references(`${oldTableName}.id`);
      table.index(['volunteer_id']);
    });

    // Step 4: Remove the 'phone_number' column from the 'constituent' table
    await knex.schema.alterTable('constituent', (table) => {
      table.dropColumn('phone_number');
    });
  }
};

**Comment by beachsideproperty** [comment]
@Alex-is-Gonzalez thank you, I added the phone number to the rename-volunteer-table migration!

**Comment by Alex-is-Gonzalez** [comment]
Can you uncommit your package-lock.json file? I just need to merge your other file. If were to push both files up it could accidentally break the containers and dependencies set up!

**Comment by davidchapuis** [comment]
Errors fixed in #837

**Pull request closed without merging**
